### ISSUE TITLE
The Dockerfile chains commands together

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/powerstrip#12]
The project's Dockerfile chains a bunch of commands together:

```
# Install security updates and required packages
RUN         apt-get update && \
            apt-get -y upgrade && \
            apt-get -y install -q build-essential && \
            apt-get -y install -q python-dev libffi-dev libssl-dev python-pip
```

These should be individual RUN commands so that if any step fails, we can still fallback on the cache. Chaining commands doesn't give any benefit.

**Comment by progrium** [comment]
This is a fundamentally different approach than we take btw.
