### ISSUE TITLE
Run "pull" tests

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/powerstrip#48]
See 3517f82, etc.

Running `pull` tests will be slightly complicated by the need to clean up after each test run.

**Comment by progrium** [comment]
Yes, my pull tests only work online, but I don't believe they need to clean
up for useful reproducible tests. It will stream output even if the image
is already pulled.

https://github.com/gliderlabs/powerstrip/blob/golang/tests/no-adapters.sh#L29

On Tue, Feb 10, 2015 at 11:08 PM, lukemarsden <notifications@github.com>
wrote:

> See 3517f82
> <https://github.com/ClusterHQ/powerstrip/commit/3517f826e769054983530dccbe6d77251d9c4998>,
> etc.
>
> Running pull tests will be slightly complicated by the need to clean up
> after each test run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ClusterHQ/powerstrip/issues/48>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by lukemarsden** [comment]
thanks @progrium!

fwiw, https://github.com/ClusterHQ/powerstrip/commit/dc15847f31c6b3a099d2ea112877b55fc75f78d1 is the approach I took on our side (which closes this issue). I can believe that pull does streaming output even if the image is already pulled, but it would be nice to verify it programmatically.

@progrium fyi, after 0.0.2 release I plan to stop working on powerstrip twisted version and focus on verifying that the golang version is equivalent, then switch.
