### ISSUE TITLE
Tag v0.0.2 not found in repository clusterhq/powerstrip-slowreq 

### ISSUE THREAD

**Issue by aanm** [ClusterHQ/powerstrip#58]
While trying it out Powerstrip as instructed in https://github.com/ClusterHQ/powerstrip#try-it-out , I got an error:

sudo docker run -d --name powerstrip-slowreq \
           --expose 80 \
         clusterhq/powerstrip-slowreq:v0.0.2
Unable to find image 'clusterhq/powerstrip-slowreq:v0.0.2' locally
Pulling repository clusterhq/powerstrip-slowreq
FATA[0001] Tag v0.0.2 not found in repository clusterhq/powerstrip-slowreq

**Comment by binocarlos** [comment]
Hey,

thanks for finding this, it's an error in the Readme - I will correct this in the morning.  In the meantime - you can replace `clusterhq/powerstrip-slowreq:v0.0.2` with `clusterhq/powerstrip-slowreq:v0.0.1` or `clusterhq/powerstrip-slowreq:latest` to see the demo working.

**Comment by aanm** [comment]
Yep that's what I did ;-)
I'll close it tomorrow

**Comment by binocarlos** [comment]
Hey so the Readme now says `v0.0.1`

**Comment by aanm** [comment]
Thank you
